kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: futureweirole-pod-reader
  tenant: futurewei
  namespace: default 
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
