kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: futurewei-reader
  tenant: futurewei
  namespace: default 
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
