kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: futureweirolebinding-xiaoning
  namespace: default 
  tenant: futurewei
subjects:
- kind: User
  name: xiaoning 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: futurewei-reader 
  apiGroup: rbac.authorization.k8s.io
