kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: futureweirolebinding-pengdu
  namespace: default 
  tenant: futurewei
subjects:
- kind: User
  name: pengdu 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: futureweirole-pod-reader
  apiGroup: rbac.authorization.k8s.io
