kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
  tenant: [change me] 
  namespace: default 
rules:
- apiGroups: ["*"]
  resources: ["pod"]
  verbs: ["get", "list", "watch"]
