kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
  tenant: tenant-qian-5  
  namespace: default 
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
