kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-pod-reader
  namespace: default 
  tenant: tenant-qian-5 
subjects:
- kind: User
  name: john 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: reader 
  apiGroup: rbac.authorization.k8s.io
